//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsJournalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassessType
    {
        public ClassessType()
        {
            this.GradlesSubjects = new HashSet<GradlesSubjects>();
        }
    
        public decimal type_id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<GradlesSubjects> GradlesSubjects { get; set; }
    }
}
