//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsJournalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradlesSubjects
    {
        public decimal student_ID { get; set; }
        public decimal lead_ID { get; set; }
        public decimal type_id { get; set; }
        public string gradle_subject { get; set; }
        public Nullable<System.DateTime> gradle_subject_date { get; set; }
    
        public virtual ClassessType ClassessType { get; set; }
        public virtual Students Students { get; set; }
        public virtual Leaders Leaders { get; set; }
    }
}
