//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsJournalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaders
    {
        public Leaders()
        {
            this.GradlesProjects = new HashSet<GradlesProjects>();
            this.GradlesSubjects = new HashSet<GradlesSubjects>();
            this.MembersInProject = new HashSet<MembersInProject>();
            this.Subjects = new HashSet<Subjects>();
            this.Projects = new HashSet<Projects>();
        }
    
        public decimal lead_ID { get; set; }
        public string lead_name { get; set; }
        public string lead_surname { get; set; }
        public string lead_degree { get; set; }
        public string lead_login { get; set; }
        public string lead_password { get; set; }
    
        public virtual ICollection<GradlesProjects> GradlesProjects { get; set; }
        public virtual ICollection<GradlesSubjects> GradlesSubjects { get; set; }
        public virtual ICollection<MembersInProject> MembersInProject { get; set; }
        public virtual ICollection<Subjects> Subjects { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
