//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsJournalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.GradlesProjects = new HashSet<GradlesProjects>();
            this.MembersInProject = new HashSet<MembersInProject>();
        }
    
        public decimal project_ID { get; set; }
        public Nullable<decimal> subject_ID { get; set; }
        public Nullable<decimal> lead_ID { get; set; }
        public string project_title { get; set; }
        public Nullable<decimal> project_students_number { get; set; }
    
        public virtual ICollection<GradlesProjects> GradlesProjects { get; set; }
        public virtual Leaders Leaders { get; set; }
        public virtual ICollection<MembersInProject> MembersInProject { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
