//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsJournalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public Students()
        {
            this.GradlesProjects = new HashSet<GradlesProjects>();
            this.GradlesSubjects = new HashSet<GradlesSubjects>();
            this.MembersInProject = new HashSet<MembersInProject>();
        }
    
        public decimal student_ID { get; set; }
        public Nullable<decimal> group_id { get; set; }
        public string student_name { get; set; }
        public string student_surname { get; set; }
        public string student_index_number { get; set; }
        public string student_login { get; set; }
        public string student_password { get; set; }
    
        public virtual DeanGroup DeanGroup { get; set; }
        public virtual ICollection<GradlesProjects> GradlesProjects { get; set; }
        public virtual ICollection<GradlesSubjects> GradlesSubjects { get; set; }
        public virtual ICollection<MembersInProject> MembersInProject { get; set; }
    }
}
