//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsJournalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public decimal subject_ID { get; set; }
        public Nullable<decimal> lead_ID { get; set; }
        public string subject_name { get; set; }
    
        public virtual Leaders Leaders { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
